#!/bin/bash
# Stage the internal extras assets from this (dev) machine into assets/.
# Assets are NOT versioned (see root .gitignore): they carry internal IPs,
# device GUIDs, platform topology detail and MCP credentials, and this repo
# has a GitHub remote. Run this before packaging; build-extras.sh requires it.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSETS="$HERE/assets"
SKILL_SRC="${NANOBOT_SKILL_SRC:-$HOME/.nanobot/workspace/skills}"
CLI_SRC="${NANOBOT_CLI_SRC:-$HOME/.nanobot/cli-apps}"
MCP_SRC="${NANOBOT_MCP_SRC:-$HOME/.nanobot/mcp}"
DCT_SRC="${NANOBOT_DCT_SRC:-$HOME/.nanobot/workspace/dct-north-cli}"
ASSET_SRC="${NANOBOT_ASSET_SRC:-$HOME/.local/share/cli-anything-asset-historical-data}"

SKILLS=(alert-analysis dynamic-monitor doc-page cli-app-dct-north-cli cli-app-chart cli-app-cli-anything-asset-historical-data)
PY="${NANOBOT_STAGE_PYTHON:-python3}"

die() { echo "stage-assets: $*" >&2; exit 1; }

for d in "$DCT_SRC" "$ASSET_SRC" "$SKILL_SRC" "$CLI_SRC/chart" "$MCP_SRC/fastgpt-knowledge"; do
  [ -d "$d" ] || die "missing source directory: $d"
done
for s in "${SKILLS[@]}"; do
  [ -f "$SKILL_SRC/$s/SKILL.md" ] || die "missing skill: $SKILL_SRC/$s/SKILL.md"
done
[ -f "$MCP_SRC/fastgpt-knowledge/config.json" ] || die "missing MCP credentials: $MCP_SRC/fastgpt-knowledge/config.json"

echo "==> resetting assets/"
rm -rf "$ASSETS"
mkdir -p "$ASSETS"/{wheels,cli-apps,skills,mcp}

echo "==> building internal CLI wheels"
"$PY" -m pip wheel "$DCT_SRC" --no-deps -w "$ASSETS/wheels" -q
"$PY" -m pip wheel "$ASSET_SRC" --no-deps -w "$ASSETS/wheels" -q

echo "==> copying chart CLI"
cp -r "$CLI_SRC/chart" "$ASSETS/cli-apps/chart"

echo "==> copying ${#SKILLS[@]} skills"
for s in "${SKILLS[@]}"; do cp -r "$SKILL_SRC/$s" "$ASSETS/skills/$s"; done

echo "==> copying MCP server"
cp -r "$MCP_SRC/fastgpt-knowledge" "$ASSETS/mcp/fastgpt-knowledge"

echo "==> cleaning cruft and sensitive files"
# Skills ship their own .gitignore documenting what must not leave the machine
# (e.g. dynamic-monitor/.env holds site URL/username/password, alert-analysis
# output/ holds generated alert data packages). Honour those exclusions here.
find "$ASSETS" -name "__pycache__" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$ASSETS" -name "*.pyc" -delete 2>/dev/null || true
find "$ASSETS" -name "*.pyo" -delete 2>/dev/null || true
find "$ASSETS" -name ".DS_Store" -delete 2>/dev/null || true
find "$ASSETS" -name "._*" -delete 2>/dev/null || true
find "$ASSETS" -name ".git" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$ASSETS" -name "node_modules" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$ASSETS" -name ".env" -delete 2>/dev/null || true
find "$ASSETS" -name "*.env" -delete 2>/dev/null || true
find "$ASSETS" -type d -name "output" -prune -exec rm -rf {} + 2>/dev/null || true

echo "==> verifying (no platform binaries, no cruft, no credentials)"
if find "$ASSETS" \( -name "*.so" -o -name "*.dylib" -o -name "*.pyd" -o -name "*.exe" \) | head -1 | grep -q .; then
  die "platform binaries found — the single cross-platform bundle assumption is broken"
fi
if find "$ASSETS" \( -name "*.pyc" -o -name "__pycache__" -o -name ".git" \) | head -1 | grep -q .; then
  die "cruft still present after cleaning"
fi
if find "$ASSETS" -name "._*" | head -1 | grep -q .; then
  die "AppleDouble (._*) files still present — they break wheel globbing"
fi
if find "$ASSETS" \( -name ".env" -o -name "*.env" \) | head -1 | grep -q .; then
  die "credential file (.env) still present — refusing to stage"
fi
if find "$ASSETS" -type d -name output | head -1 | grep -q .; then
  die "run artifacts (output/) still present — refusing to stage"
fi

echo "==> writing manifest"
{
  echo "# Extras asset manifest (generated by stage-assets.sh)"
  echo
  echo "Staged: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Sources: skills=$SKILL_SRC cli-apps=$CLI_SRC mcp=$MCP_SRC"
  echo "         dct-north-cli=$DCT_SRC asset-historical-data=$ASSET_SRC"
  echo
  echo "## wheels/"
  echo
  for w in "$ASSETS"/wheels/*.whl; do
    echo "- \`$(basename "$w")\` sha256=\`$(shasum -a 256 "$w" | cut -d' ' -f1)\`"
  done
  echo
  echo "## skills/"
  echo
  for s in "${SKILLS[@]}"; do
    echo "- \`$s\`: $(wc -l < "$ASSETS/skills/$s/SKILL.md" | tr -d ' ') lines SKILL.md"
  done
} > "$ASSETS/SOURCES.md"

echo "==> done: $(du -sh "$ASSETS" | cut -f1)"
